# Nombre de la app (útil para logs y Eureka después)
spring.application.name=emppp
# Conexión a PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/ppp
spring.datasource.username=fourkodika
spring.datasource.password=*practicas123@*

# Configuración del pool de conexiones (opcional pero útil)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logs para ver las queries y sus parámetros
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Puerto y contexto del microservicio
server.port=8081
server.servlet.context-path=/empresas