# ===============================
# SERVER SETTINGS
# ===============================
server.port=8083
server.servlet.context-path=/emppp

# ===============================
# SPRING CONFIGURATION
# ===============================
spring.application.name=emppp

spring.datasource.url=jdbc:postgresql://localhost:5433/ppp
spring.datasource.username=fourkodika
spring.datasource.password=*practicas123@*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# EUREKA (Disabled for now)
# ===============================
eureka.client.enabled=false

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE