spring.application.name=personas-ms
# Configuración de conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/personas_db
spring.datasource.username=personas
spring.datasource.password=P3rs0n4sM1cr0s3rv1c3
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración HikariCP
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Nivel de log para SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Puerto del servidor
server.port=8080

# Si luego activas Eureka y Config Server, solo descomenta lo siguiente:
# spring.cloud.config.enabled=false