spring:
  datasource:
    username: ${pms.username}
    hikari:
      maximum-pool-size: ${pms.maximum-pool-size}
      connection-timeout: ${pms.connection-timeout}
    url: ${pms.url}
    password: ${pms.password}
    driver-class-name: org.postgresql.Driver

  application:
    name: personas-ms
    jwt:
      secret: qA72rBv93xL09FkMeZtN84yWc5gXp1sThUJaVmCRd3oPiKELfGwHnb6Yt2UzXSvQ

  profiles:
    default: default

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"
    #import: "optional:configserver:http://localhost:7777"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /personas-ms
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
