spring:
  datasource:
    username: ${oms.username}
    hikari:
      maximum-pool-size: ${oms.maximum-pool-size}
      connection-timeout: ${oms.connection-timeout}
    url: ${oms.url}
    password: ${oms.password}
    driver-class-name: org.postgresql.Driver

  application:
    name: ofertapostulacion-ms

  profiles:
    default: default

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"
    #import: "optional:configserver:http://localhost:7777"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /ofertapostulacion-ms
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/