# Puerto del microservicio
server.port=8084

# Nombre del microservicio
spring.application.name=practicasevidencias-ms

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/practicas_db
spring.datasource.username=practicas
spring.datasource.password=Pr4ct1c4sM1cr0s3rv1c3
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
